# Generated by Django 4.2.5 on 2023-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='max_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
