# Generated by Django 4.2.5 on 2023-11-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
